version: "3"
name: "safe-routes"
services:
  fastapi-app:
    container_name: safe-routes
    image: nikbenlioglu/safe-routes:latest
    ports:
      - "8000:8000"
    networks:
      - internal
    environment:
      - HOST=host.docker.internal
networks:
  internal:
    driver: bridge